project:
  type: website
  output-dir: docs

website:
  title: "Cámaras trampa CAPES"
  
 
  page-footer:
    right: "Página construida con [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Gabriel Andrade-Ponce"
    background: "#D9E3E4" 
  
  
  navbar:
    background: "#6188bc"
    
    right:
      - href: DigiKam.qmd
        text: DigiKam
      - href: IAR_doc.qmd
        text: Script IAR
      
      
    tools:
      - icon: github
        href: https://github.com/gpandradep/Curso-Congreso-Chihuahhua
        text: "GitHub"

format:
  html:
    theme: journal
    mainfont: "Fira Sans"
    fontsize: 23px
    margin-right: 0px
    css: styles.css
    toc: true
lang: es
editor: visual

